id: P010451
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN2394
  title: བཀའ་སྲུང་བཙན་རྒོད་ཀྱི་མངོན་རྟོགས།
  author: ''
  volumes:
    ad1e53b69c8a44afb76125f9025a9a6b:
      image_group_id: I3CN2396
      title: ''
      volume_number: 1
      total_pages: 179
