id: P010451
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-19 20:50:33.609271
source_metadata:
  id: bdr:W3CN2394
  title: བཀའ་སྲུང་བཙན་རྒོད་ཀྱི་མངོན་རྟོགས།
  author: ''
  volumes:
    ad1e53b69c8a44afb76125f9025a9a6b:
      image_group_id: I3CN2396
      title: ''
      volume_number: 1
      total_pages: 179
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
